Feature/web components
manuelbarzi/skylab-bootcamp-202004 pull request #144
Opened 2020-05-04 07:17 UTC by PolPedro

2020-05-06 11:31 UTC, manuelbarzi commented on staff/pol-pedro/web-components/my-app-react/components/App.jsx
> +            let follow = []
use `const` by default, not `let` (only use `let` if you required to re-assign a new value to this ref later)

2020-05-06 11:31 UTC, manuelbarzi commented on staff/pol-pedro/web-components/my-app-react/components/App.jsx
> +            let newTweet = {username: this.state.user.username, text: tweet, date: new Date()}
again, use `const` by default, not `let`. same in the other files.

2020-05-06 11:31 UTC, manuelbarzi commented on staff/pol-pedro/web-components/my-app-react/components/Component.js
> +    creat(template) {
did you mean `create` instead of `creat`?

2020-05-06 11:31 UTC, manuelbarzi commented on staff/pol-pedro/web-components/my-app-react/components/App.jsx
> +            {this.state.clickNav && <GoogleComp onGoogle = {this.googleSearch} results = {this.state.google} query = {this.state.navQuery} loadSpiner = {this.loadQuery} spiner={this.state.navOnserch}
did you mean `loadSpinner` instead of `loadSpiner`?

2020-05-06 11:31 UTC, manuelbarzi commented on staff/pol-pedro/web-components/my-app-react/components/App.jsx
> +        this.state.navOnserch ? this.setState({navOnserch : ''}) : this.setState({navOnserch : 'fas fa-spinner fa-5x'})
why are you saving CSS classes in state? you may avoid that as much as possible. but instead just use flags in state. not specific styles.

2020-05-18 19:13 UTC, PolPedro commented on staff/pol-pedro/web-components/my-app-react/components/App.jsx
> +            let follow = []
done

2020-05-18 19:14 UTC, PolPedro commented on staff/pol-pedro/web-components/my-app-react/components/App.jsx
> +            let newTweet = {username: this.state.user.username, text: tweet, date: new Date()}
done

2020-05-18 19:16 UTC, PolPedro commented on staff/pol-pedro/web-components/my-app-react/components/App.jsx
> +            {this.state.clickNav && <GoogleComp onGoogle = {this.googleSearch} results = {this.state.google} query = {this.state.navQuery} loadSpiner = {this.loadQuery} spiner={this.state.navOnserch}
done

2020-05-18 19:16 UTC, PolPedro commented on staff/pol-pedro/web-components/my-app-react/components/Component.js
> +    creat(template) {
done

2020-05-18 19:18 UTC, PolPedro commented on staff/pol-pedro/web-components/my-app-react/components/App.jsx
> +        this.state.navOnserch ? this.setState({navOnserch : ''}) : this.setState({navOnserch : 'fas fa-spinner fa-5x'})
Okey! i will have that in mind the next time. Thanks for your feedback

2020-05-19 10:15 UTC, lichab requested changes
Pol, don't say 'done' if you have not attended to what we left as review. Yo did not change even one let to const and you have looot of unnecesary lets.  Also please remove all commented code, taht you also have a lot.

2020-05-19 10:17 UTC, alexiparkhio commented on staff/pol-pedro/web-components/my-app-react/components/Home.jsx
> +
please remove this huge block of commented code

2020-05-19 10:17 UTC, alexiparkhio commented on staff/pol-pedro/web-components/my-app-react/components/App.jsx
> +            let follow = []
Hi Pol! Are you sure you pushed those changes? I still see the `let` here

2020-05-19 10:17 UTC, alexiparkhio commented on staff/pol-pedro/web-components/my-app-react/components/Landing.jsx
> +
remove commented code

2020-05-19 10:17 UTC, alexiparkhio commented on staff/pol-pedro/web-components/my-app-react/components/Register.jsx
> +        // this.props.onSumbmit (name, surname, email, password)
remove commented code

2020-05-19 10:17 UTC, alexiparkhio commented on staff/pol-pedro/web-components/my-app-react/components/google-comp.jsx
> +function GoogleComp ({ onGoogle, results, query, loadSpinner, spiner }) { //hacer un calss para poder usar el spiner cambiando el state
component file names in Proper Case (Google-Comp.jsx)

2020-05-19 10:17 UTC, alexiparkhio commented on staff/pol-pedro/web-components/my-app-react/components/style/Home.sass
> +// @keyframes spin
remove commented code

2020-05-19 10:17 UTC, alexiparkhio commented on staff/pol-pedro/web-components/my-app-react/logic/google.js
> +
remove commented code

2020-05-19 10:17 UTC, alexiparkhio commented on staff/pol-pedro/web-components/my-app-react/logic/retrive-user.js
> +function retive(token, callback) {
did you mean `retrieve-user.js` ?

2020-05-19 10:17 UTC, alexiparkhio commented on staff/pol-pedro/web-components/my-app-react/logic/retrive-user.js
> +function retive(token, callback) {
also function should be called `retrieveUser`

2020-05-19 10:17 UTC, alexiparkhio commented on staff/pol-pedro/web-components/my-app-react/logic/search-users.js
> +
remove commented code

2020-05-19 10:17 UTC, alexiparkhio commented on staff/pol-pedro/web-components/my-app-react/main.jsx
> +
remove commented code

2020-07-15 10:09 UTC, merged